"""
rag/store.py

Schema-aware vector retrieval using ChromaDB + nomic-embed-text.

On this hardware the RAG layer serves two purposes:
1. Provides Llama 3.1 8B with precise field context for unusual queries
2. Helps identify which fields are most relevant for aggregation selection

The embedding model (nomic-embed-text) runs on CPU via Ollama —
it doesn't need the GPU, leaving VRAM for Llama 3.1 8B.
"""

import json
import os
import sys
import argparse
import chromadb
from chromadb import Settings as ChromaSettings
from opensearchpy import OpenSearch

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.settings import settings
from llm.client import ollama

COLLECTION_NAME = "siem_schema_v2"

# ── Field catalog ─────────────────────────────────────────────────────────────
# Loaded from data/field_catalog.json (generated by data/build_field_catalog.py)
# Falls back to minimal hardcoded catalog if JSON not found.

_CATALOG_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "field_catalog.json")

def _load_field_catalog():
    if os.path.exists(_CATALOG_PATH):
        with open(_CATALOG_PATH) as f:
            catalog = json.load(f)
        print(f"Loaded field catalog: {len(catalog)} fields from {_CATALOG_PATH}")
        return catalog
    print("Warning: field_catalog_expanded.json not found, using minimal fallback catalog")
    return {
        "@timestamp": {
            "description": "Primary timestamp of the security event",
            "nl_phrases": ["when", "time", "date", "occurred", "happened", "recent", "latest"],
            "query_type": "range",
        },
        "rule.level": {
            "description": "Severity level 0-15, higher is more severe",
            "nl_phrases": ["severity", "level", "critical", "high severity"],
            "query_type": "range",
        },
        "data.srcip": {
            "description": "Source IP address where the attack originated",
            "nl_phrases": ["source ip", "from ip", "attacker ip", "origin ip"],
            "query_type": "term",
        },
        "rule.groups": {
            "description": "Event categories e.g. authentication_failed malware brute_force",
            "nl_phrases": ["category", "type", "attack type", "event type"],
            "query_type": "term",
        },
        "agent.name": {
            "description": "Hostname of the Wazuh agent",
            "nl_phrases": ["hostname", "machine", "computer", "endpoint", "host"],
            "query_type": "term",
        },
    }

FIELD_CATALOG = _load_field_catalog()


# ── Embedding function ─────────────────────────────────────────────────────────

class OllamaEmbedder:
    """ChromaDB-compatible embedding function using local Ollama."""
    def name(self) -> str:
        return "ollama-embedder"

    def __call__(self, input: list[str]) -> list[list[float]]:
        return [ollama.embed(text) for text in input]


# ── Vector store ───────────────────────────────────────────────────────────────

def get_collection():
    client = chromadb.PersistentClient(
        path=settings.chroma_path,
        settings=ChromaSettings(anonymized_telemetry=False),
    )
    return client.get_or_create_collection(
        name=COLLECTION_NAME,
        embedding_function=OllamaEmbedder(),
        metadata={"hnsw:space": "cosine"},
    )


def build_store(es_client: OpenSearch = None, force: bool = False):
    """
    Build or rebuild the schema vector store.

    Args:
        es_client: Optional — for pulling live index mappings
        force:     Clear and rebuild if True
    """
    client = chromadb.PersistentClient(
        path=settings.chroma_path,
        settings=ChromaSettings(anonymized_telemetry=False),
    )

    if force:
        try:
            client.delete_collection(COLLECTION_NAME)
            print(f"Deleted existing collection.")
        except Exception:
            pass

    collection = client.get_or_create_collection(
        name=COLLECTION_NAME,
        embedding_function=OllamaEmbedder(),
    )

    # Merge catalog with live mappings if available
    all_fields = dict(FIELD_CATALOG)
    if es_client:
        try:
            mappings = es_client.indices.get_mapping(index=settings.es_index)
            for idx_data in mappings.values():
                props = idx_data.get("mappings", {}).get("properties", {})
                for field in _flatten_props(props):
                    if field not in all_fields:
                        all_fields[field] = {
                            "description": f"Field: {field}",
                            "nl_phrases": [field],
                            "query_type": "term",
                            "examples": [],
                        }
        except Exception as e:
            print(f"Warning: Could not fetch live mappings ({e}). Using catalog only.")

    print(f"Indexing {len(all_fields)} fields into ChromaDB...")

    for field_name, meta in all_fields.items():
        safe_id = field_name.replace(".", "_").replace("@", "at_")
        embed_text = (
            f"Field: {field_name}. "
            f"Description: {meta['description']}. "
            f"Natural language: {', '.join(meta.get('nl_phrases', []))}. "
            f"Examples: {', '.join(str(e) for e in meta.get('examples', [])[:3])}"
        )
        try:
            collection.upsert(
                ids=[safe_id],
                documents=[embed_text],
                metadatas=[{
                    "field": field_name,
                    "description": meta["description"],
                    "query_type": meta["query_type"],
                    "examples": json.dumps(meta.get("examples", [])[:3]),
                }],
            )
        except Exception as e:
            print(f"  Warning: Could not index field {field_name}: {e}")

    print(f"Store built. {collection.count()} fields indexed.")


def retrieve_fields(query: str, n: int = 8) -> str:
    """
    Retrieve relevant schema fields for a natural language query.
    Returns a formatted string for injection into the LLM prompt.
    """
    try:
        collection = get_collection()
        if collection.count() == 0:
            return ""

        results = collection.query(
            query_texts=[query],
            n_results=min(n, collection.count()),
        )
        lines = ["Relevant fields for this query:"]
        for meta in results["metadatas"][0]:
            examples = json.loads(meta.get("examples", "[]"))
            ex_str = f" Examples: {', '.join(str(e) for e in examples)}" if examples else ""
            lines.append(f"  - {meta['field']} ({meta['query_type']}): {meta['description']}.{ex_str}")
        return "\n".join(lines)
    except Exception:
        return ""


def _flatten_props(props: dict, prefix: str = "") -> list[str]:
    fields = []
    for name, config in props.items():
        full = f"{prefix}.{name}" if prefix else name
        fields.append(full)
        if "properties" in config:
            fields.extend(_flatten_props(config["properties"], full))
    return fields


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--build", action="store_true")
    parser.add_argument("--rebuild", action="store_true")
    parser.add_argument("--query", type=str)
    args = parser.parse_args()

    if args.build or args.rebuild:
        es = OpenSearch(
            hosts=[{"host": settings.es_host, "port": settings.es_port}],
            http_auth=(settings.es_user, settings.es_password),
            use_ssl=True,
            verify_certs=False,
            ssl_show_warn=False,
        )
        build_store(es_client=es, force=args.rebuild)

    if args.query:
        print(retrieve_fields(args.query))